### ISSUE TITLE
WIP: Longitudinal data management

### ISSUE THREAD

**Issue by smoyte** [getodk/roadmap#21]

**Comment by admbtlr** [comment]
## User Stories

*As a health worker, I want to be able to collect a medical record every time a patient visits my health facility, so that I can keep track of the patient's progress over time*

*As a census taker, I want to visit a village every year and record population data*

*As a vaccine delivery driver, I want to keep track of the quantities of vaccines that I deliver to cold storage facilities during my weekly deliveries*

*As a regional vaccine administrator, I want to download CSV files that show the quantities of vaccine that have been delivered to all the cold storage facilities in my region over the last six months*

## Proposed Implementation

For the sake of this explanation, I'm going to use the following terminology:
- **Entity** refers to the thing about which data is collected. The kind of thing -- the "entity type" -- will depend on the use case. So in the above user stories, the entity types would be "patient", "village", "cold storage facility", "cold storage facility"
- **Record** refers to one round of data collection. So in the above user stories, a record would be 
    1. the details of patient's visit to a health facility
    2. an annual set of population data for a village
    3. the quantities delivered to a health facility in a given week 
    4. again, the quantities delivered to a health facility in a given week

The simplest solution is probably to have two separate forms, one to collect the details of an entity ("the Entity Form") and one to collect the details of each visit ("the Record Form"). A Record must have one (and only one) Entity associated with it. An Entity can have multiple Records associated with it.

### The Entity Form

Forms for creating entities must have certain fields marked as "identifiers". This would be for example a patient's name, or a village name and region, or a cold storage facility name and ID number.

### The Record Form

Forms for creating records must have one attribute called `entity_type_id`; this attribute can only contain the UUID of an Entity Form. They must also have one field called `entity_id`. This field can only contain the `instanceID` of an Entity.

**Comment by admbtlr** [comment]
Still working on it!

**Comment by smoyte** [comment]
Actually this might be a duplicate?

**Comment by smoyte** [comment]
See https://github.com/opendatakit/roadmap/issues/23 ?? Should we close this one out?

**Comment by admbtlr** [comment]
You’re absolutely right, well spotted!
