### ISSUE TITLE
Nicer looking, more consistent form/instance lists

### ISSUE THREAD

**Issue by cooperka** [getodk/roadmap#29]
### Resources

- [Mocks for each page](https://app.moqups.com/sassafras/4WPu8QH3er/view/page/ae400e3ba)
- [Material Design color palettes](https://material.io/design/color/the-color-system.html#tools-for-picking-colors)
- [Material Design icon guidelines](https://material.io/design/iconography/system-icons.html#color)
- [Material Design icon list](https://material.io/tools/icons/)

### General goal

- To make form and instance lists look nicer, be more consistent, and be more intuitive to use
- To conform to Material Design specs as much as possible
- To do this while making minimal changes to the current UI

<img width="342" alt="Mockup of new UI" src="https://user-images.githubusercontent.com/2047062/49525016-d4853b80-f87a-11e8-995e-7eb46b06c271.png">

*Mockup of new UI*

### Proposed implementation

Add an icon to the start of each row in form lists. This includes:

- Fill Blank Form
- Edit Saved Form
- Send Finalized Form
- View Sent Form
- Get Blank Form
- Delete Saved Form: Saved Forms
- Delete Saved Form: Blank Forms

The icons will change depending on the form/instance state to make it more clear to users what state the form is in:

| Icon | Icon description | Form state | Screens it appears on |
|---|---|---|---|
| ![clip-blank](https://user-images.githubusercontent.com/2047062/49473596-79066f80-f7e0-11e8-9cfd-cdc1ffaf3973.png) | 0/3 checked boxes | Blank | Fill Blank Form<br>Get Blank Form<br>Delete: Blank Forms |
| ![clip-text](https://user-images.githubusercontent.com/2047062/49473602-799f0600-f7e0-11e8-8783-5364a30c7ece.png) | 2/3 checked boxes | Incomplete | Edit Saved Form<br>Delete: Saved Forms |
| ![clip-pkg](https://user-images.githubusercontent.com/2047062/49474293-4c535780-f7e2-11e8-8426-0ea1d56ab612.png) | Package | Finalized | Edit Saved Form<br>Send Finalized Form<br>Delete: Saved Forms |
| ![clip-sms](https://user-images.githubusercontent.com/2047062/49473601-79066f80-f7e0-11e8-95bf-f4783852c2af.png) | Message | Sending via SMS* | Edit Saved Form<br>Send Finalized Form<br>Delete: Saved Forms |
| ![clip-check](https://user-images.githubusercontent.com/2047062/49474291-4c535780-f7e2-11e8-958f-a65814e0d622.png) | Cloud check | Submitted | Send Finalized Form<br>View Sent Form<br>Delete: Saved Forms |
| ![clip-error](https://user-images.githubusercontent.com/2047062/49474292-4c535780-f7e2-11e8-9c9b-764c31c122a2.png) | Cloud exclamation | Failed to submit | Send Finalized Form<br>Delete: Saved Forms |

\* The SMS icon is optional; the current Send Finalize Form UI includes this icon, but it's redundant with the progress bar. It can either be kept for consistency or removed for simplicity.

### Changes to existing screens

- Most screens: Simply add icons to the start of each row as described above
- Send Finalized Form screen: More signifcant change, because it currently looks different from the rest (see below); it would once again be consistent after this change

<img width="340" alt="Existing Send Finalized Form screen" src="https://user-images.githubusercontent.com/2047062/49045032-a67a6a00-f19d-11e8-9213-c15481b8f603.png">

*Existing screen*

### Icon details

The only icons that are currently used to indicate form state are on the Send Finalized Form screen (screenshot above). We took the existing "check", "sms", and "error" icons from there and added the clipboard to unify them into the icon set for this proposal.

The new icons use Material Design's blue/green/red/amber **500** for icon colors, which is consistent with the existing blue icons and status bar color.

### Current icons

If you want to examine the code, icons are currently used in `InstanceUploaderAdapter`.

For regular submissions:

```java
    case STATUS_SUBMISSION_FAILED:
        R.drawable.exclamation;

    case STATUS_SUBMITTED:
        R.drawable.check;

    default:
        R.drawable.pencil;
```

For SMS submissions:

```java
    case Activity.RESULT_OK:
        R.drawable.check;

    case RESULT_QUEUED:
    case RESULT_OK_OTHERS_PENDING:
    case RESULT_SENDING:
    case RESULT_MESSAGE_READY:
        R.drawable.message_text_outline;

    default:
        R.drawable.exclamation;
```

### Known variants

The following are all the possible states for form instances (public vars from `InstanceProviderAPI`):

- (blank form, not yet an instance)
- STATUS_INCOMPLETE
- STATUS_COMPLETE (i.e. finalized)
- STATUS_SUBMITTED
- STATUS_SUBMISSION_FAILED

The following are all the possible states for SMS submissions (public vars from `SmsService`):

- RESULT_QUEUED
- RESULT_OK_OTHERS_PENDING
- RESULT_INVALID_GATEWAY
- RESULT_MESSAGE_READY
- RESULT_SENDING

The table at the beginning covers each of these states.

**Comment by smoyte** [comment]
@yanokwa @adamvert I wonder if this would suffice for making the overlays sufficiently visible:

![image](https://user-images.githubusercontent.com/702320/49176638-3bee3900-f319-11e8-9391-3facba1ef225.png)

(Note that we haven't changed to yellow for SMS yet but still plan to do that.)

The issue with putting the status inside the clipboard was that it didn't really make it any bigger or more legible (less so in the case of the exclamation mark). 

I think we can still have the familiar thing-with-overlay idea without sacrificing legibility if we just make the overlays big enough.

Thoughts?

**Comment by tiritea** [comment]
Since I need to do something very similar in my iOS XForms app I thought I'd share. I'm certainly not suggesting y'all follow suit, but it perhaps gives another perspective/data point to think about:

submitted (ie now in the cloud...):
![cloud checked filled-25 3x](https://user-images.githubusercontent.com/18408635/49178555-ebc4b480-f3b4-11e8-95df-54b50156f136.png)

submitting (ie uploading to cloud):
![icons8-upload-to-cloud-filled-25 3x](https://user-images.githubusercontent.com/18408635/49178633-262e5180-f3b5-11e8-8b30-e266e9e458e4.png)

complete (all required & relevant questions answered):
![ok filled-25 3x](https://user-images.githubusercontent.com/18408635/49178734-61c91b80-f3b5-11e8-8e0b-02e21e4821cb.png)

incomplete (not all required questions answered yet. pie chart shows approx % complete in 30deg increments):
![210 degrees filled-25 3x](https://user-images.githubusercontent.com/18408635/49178810-989f3180-f3b5-11e8-8cd9-998c9a33180d.png)
![60 degrees filled-25 3x](https://user-images.githubusercontent.com/18408635/49178823-a3f25d00-f3b5-11e8-915b-f989114cb9c6.png)

started (just started form, ie 0% complete):
![0 degrees filled-25 3x](https://user-images.githubusercontent.com/18408635/49178863-c84e3980-f3b5-11e8-88b9-f4bf59f8c237.png)

not started (inspection forms in my app are scheduled, so this is the icon for a scheduled inspection that you haven't started yet. Its a similar state to just started, hence visually similar icon...):
![icons8-unchecked-checkbox-black-25 3x](https://user-images.githubusercontent.com/18408635/49178949-119e8900-f3b6-11e8-8413-a8436e3923fb.png)

I dont have a failed submit state per se (app keeps trying) but it would probably be:
![icons8-error-cloud-filled-100](https://user-images.githubusercontent.com/18408635/49179125-7b1e9780-f3b6-11e8-8c2f-80ddf4027909.png)

Oh, another subtlety is that the overall 'blackness' of the icon(s) immediately conveys the form's "completeness": completed forms (in whatever submission state) are all black, empty forms are all white, and incomplete/partly complete forms are half black/half white accordingly.

I'm inclined to agree with @yanokwa in that I dont see a huge benefit to having the majority of the visual taken up with the generic form icon. In different contexts, eg a filesystem browser, arguably the *most* important information desired to convey is the file *type* (aka associated application), which is why filesystem icons predominantly represent the different file types. But in our context, *everything* is already known to be form, whereas now the most important information desired to convey is the form *status*. So I would think the status should be the dominant visual, especially on a device with limited screen real-estate like a mobile phone. The form icon is fine, but its really only useful in a context where its important to distinguish a form feature or form-related operation from something else non-form related.

But I'm also acutely aware from experience that if you want 5 wildly opposing viewpoints on something GUI related, just ask 6 people :-) End of the day, the most important thing is that it is consistent to a theme, and remember the axiom that "Good design goes unnoticed!" That is, if nobody cares enough to note an annoyance, then you've probably nailed it! :-)

**Comment by yanokwa** [comment]
The bigger overlays in this last iteration are better, but still prefer just the status icons. To capture the state of a blank form and an incomplete form, I'm imagining that a circle with a "document" with some number of lines would work.

@adamvert's idea was to color the clipboard and put just the mark (no circle) inside. Would that work better? If it's terrible, a mockup there would help convince me, @smoyth.

The Finalized icon suggests that the form is packaged and ready to go. That is true, but finalized forms can also be edited. I wonder if 1 lines for incomplete and 3 lines for finalized might be better.

@tiritea's suggestion of the checkbox in the cloud makes me think that people might think the green check that we have just means the form is complete (e.g. finalized). A cloud icon might be better.

**Comment by yanokwa** [comment]
The bigger overlays in this last iteration are better, but I'd still prefer just the status icons. To capture the state of a blank form and a incomplete form, I'm hoping that a circle with a "document" with some number of lines. 

@adamvert's idea was to color the clipboard and put just the mark (no circle) inside. Would that work better? If it's terrible, a mockup there would help convince me, @smoyth.

The Finalized icon suggests that the form is packaged and ready to go. That is true, but finalized forms can also be edited. I wonder if, 1 lines for incomplete and 3 lines for finalized might be better.

@tiritea's suggestion of the checkbox in the cloud makes me think that people might think the green check that we have just means the form is complete (e.g. finalized).

**Comment by yanokwa** [comment]
@smoyth When a sent form is deleted (or the form is sent and encrypted), there is an icon that shows up on the side of the file list. Are you also proposing to change this?
<img width="373" alt="screen shot 2018-11-29 at 3 05 07 pm" src="https://user-images.githubusercontent.com/32369/49257797-3ad80d00-f3e8-11e8-8b35-bb4407d2c213.png">

**Comment by tiritea** [comment]
> The Finalized icon suggests that the form is packaged and ready to go. That is true, but finalized forms can also be edited.

Can a 'Finalized' form in Collect become  unfinalized after, say, going back and editting something which causes a previously irrelevant required question to become relevant? [it certainly can in mine].

**Comment by cooperka** [comment]
> Can a 'Finalized' form become unfinalized

Yes, you can edit a finalized form and uncheck the "mark as finalized" box. When you save, it will no longer be finalized.

**Comment by smoyte** [comment]
@yanokwa Regarding the deleted/encrypted icon, I had forgotten about that. What would you recommend? Given there is no checkbox over there, there is plenty of room to keep that icon as is.

@tiritea Can you share a screenshot from your app? I'm curious how your full list views look including the icons.

I think I am willing to try the status-icons-only thing. Jill pointed out they should all be circles per the latest Android vibe:

![image](https://user-images.githubusercontent.com/702320/49295602-2cd7ca00-f484-11e8-9139-91ce4856b737.png)

See also the email app. I know we have circles now in the Send Finalized screen but they're a bit big. Can we make them the size of the ones in the above screenshot?

**Comment by yanokwa** [comment]
@smoyth It's an additional state that you'd have to represent (e.g., finalized and encrypted, sent and deleted) and I can't think of a great way to do that. If you can, great! If not, it seems fine for it to stay in that location, but get a bit of polish.

**Comment by tiritea** [comment]
BTW, a 'lock' badge would be a nice touch on top of *all* (my) status icons, to indicate the form data has been secure/encrypted throughout its entire lifecycle. I dont currently support encryption, but when I do I think I'll do just that! :-)

>Can you share a screenshot from your app? I'm curious how your full list views look including the icons.

Will do. I'll try to post something tomorrow.

**Comment by tiritea** [comment]
> > Can a 'Finalized' form become unfinalized
> 
> Yes, you can edit a finalized form and uncheck the "mark as finalized" box. When you save, it will no longer be finalized.

Actually, what I meant was, if you go back and edit a finalized form, then the possibility exists that a previously non-relevant - but otherwise mandatory (and unanswered) - question now becomes relevant (irregardless of the user explicitly unchecking 'Finalized'). Presumably the user cant get to the point of checking 'Finalized' until all relevant and mandatory questions are answered. So there seems to be the situation where a consequence of editing a (finalized) form may require *programmatically* unchecking 'Finalized'. Correct?

**Comment by smoyte** [comment]
@tiritea Regarding having pie chart icons representing the percentage complete of the form—how are you accomplishing that technically?

@yanokwa @cooperka I was under the impression that would be hard to achieve in Collect. Is that accurate? How hard? Should we attempt it? Unless there is a fairly easy route to this my inclination would be to sidestep it for now.

**Comment by yanokwa** [comment]
Completeness/progress of a form is a hard thing to get right because of things like repeats and branching. We had progress bars in the past and removed them because of that. I think doing it for form lists is unnecessary and should be sidestepped.

**Comment by tiritea** [comment]
> @tiritea Regarding having pie chart icons representing the percentage complete of the form—how are you accomplishing that technically?

After each control change - when I have to perform re-computations and iterate through all the controls anyway to re-evaluate relevants, etc - I count how many of the controls are relevant & required, and of those how many have a non-null result (ie 'answered'). That gives me a fractional completeness. And when N/N I know everything relevant and required is answered, so the form is 'Done'. I actually display this same current progress icon while they are filling in the form (not just on the summary submission list tab) so they can watch their progress change as they work through the form.

It is for this reason that I dont actually have an explicit "Finalize" button (!), nor corresponding state; instead, everything is fair game right up to the point you hit 'Submit'. And as a direct result I dont have to worry about programmatically forcibly 'unfinalizing' things. If they go back - at any time before submit - and change something, the progress calculation will reflect the consequences accordingly (including changing the summary progress icon from 'complete' to something else). And any form not 100% complete doesn't get added to the submit queue when they do finally hit submit.

But, as @yanokwa notes, this progress stuff can get more complicated when you have to take into account repeat groups, etc, which alas I dont yet support. :-(

> ...I think doing it for form lists is unnecessary

Oh, the progress calculation is performed whilst the form is being filled out, and the result persisted alongside the form submission instance data. So I'm not having to (re)calculate it when just displaying the form list.

**Comment by yanokwa** [comment]
> Presumably the user cant get to the point of checking 'Finalized' until all relevant and mandatory questions are answered. So there seems to be the situation where a consequence of editing a (finalized) form may require _programmatically_ unchecking 'Finalized'. Correct?

When you edit a finalized form, the button for mark as finalized keeps its state (checked). You can indeed make changes so your form is no longer valid, but when you hit save, Collect will prevent the save until the form is valid. It will, I believe, automatically take you to the question that is invalid. To save this invalid form, you can navigate to the end of the form and uncheck the mark as finalized option.

**Comment by tiritea** [comment]
> When you edit a finalized form, the button for mark as finalized keeps its state (checked). You can indeed make changes so your form is no longer valid, but when you hit save, Collect will prevent the save until the form is valid.

Gotcha. I have neither 'Finalize' nor 'Save' for that matter (again, everything is fair game till you hit 'Submit'). So I guess my workflow is a bit simpler to manage... :-)

[In my own defense, I debated this for some time... In the end I decided to simply make my app as flexible as possible; if at the end-of-the-day the user *could* in fact change whatever they like, right up to the point of submission, then eventually they'll figure this out and simply avoid prematurely saving/finalizing things till the last minute, because doing so just makes it a pain-in-the-a*** if they want to go back and edit stuff. That is, they see is no benefit *to themselves* in following these indeterminate state transitions. But our users - council inspectors - are probably a somewhat different breed than most ODK field enumerators... ;-) ].

**Comment by tiritea** [comment]
As requested, here screenshots showing my various submission (aka "inspection") states. These are actually taken from my iOS GoMobile app [the commercialized version of my iXForms. Sorry but my iXForms build is currently broke right now]. So the context is slightly different - forms are shown as part of a *schedule* here, but hopefully you can see what they all look like in a list. In iXForms they  look pretty much identical, except the second line of text is the relevant timestamp information, instead of the inspection address shown here.

First pic shows how they all appear within the GoMobile daily schedule. Note the progress/status icon is also used in the inspection summary details, and it will also appear on every screen while you open and edit the form, and updates every time you answer a question:

![img_0243 copy](https://user-images.githubusercontent.com/18408635/49480007-f1753b00-f889-11e8-893e-f0fd0ad3d8c6.PNG)

I cropped out just the schedule to give a better idea of what they'd look like shown in a simple list. [the text and background color are settable custom properties of each form to give inspectors an idea of what sort of inspection its going to be. I dont do this in iXForms]:

![img_0246](https://user-images.githubusercontent.com/18408635/49481045-fcca6580-f88d-11e8-9691-5466226a3054.PNG)

Unfortunately, its a bit tricky to capture an upload in-flight, so the 'submitting' icon isnt shown. But as a bit of extra eye-candy I *animate* the up-arrow while its being uploaded :-) [not sure if this animated gif will work, but here goes...]

![upload](https://user-images.githubusercontent.com/18408635/49480240-cccd9300-f88a-11e8-8df1-c4b9fb4778e0.gif)

[above gif is a bit coarse; I animate a set of pngs in the actual app itself. But you get the idea]

**Comment by tiritea** [comment]
For the sake of completeness (but at the risk of opening a rabbit-hole...) there's actually another form 'state' in my iXForms app, shown as:

![icons8-download-from-the-cloud-filled-100](https://user-images.githubusercontent.com/18408635/49481207-b32e4a80-f88e-11e8-889a-114e691ab889.png)

This represents a form submission that's on the server ('in the cloud') *but not yet currently loaded onto the device*. So the icon indicates both its state and the operation that will be performed on it, namely downloading it. [by implication, any form submission that is in the cloud is complete, so there's no ambiguity by not showing the check mark].

Basically, under my forms browser, my app will (attempt to) retrieve the list of form submission - via the OpenRosa `view/submissionList` API -  and display them in a list. If the user selects one it will be downloaded and displayed, using the same basic form-filler interface but now the form will be read-only. This is effectively the same behavior for a form that's just been submitted: you can open it up again to browse, but not change anything. Indeed, after submission, the main (only?) difference between a form you submitted and one that you've downloaded off the server is probably just the fact the submitter name isnt yours (!). And for this reason, any forms you download for viewing are shown using the same icon as submitted, since functionally they are now basically in identical states: they are both complete, they exist on both the device and server, and neither are editable.

![icons8-cloud-checked-filled-25 3x](https://user-images.githubusercontent.com/18408635/49481616-8a0eb980-f890-11e8-9d19-71cfb38785b7.png)

[I'm not suggesting Collect should do likewise. I simply chose to try and maximize the utility of my mobile app to encompass some of the functionality you'd normally be required to go to Aggregate to accomplish; eg browsing submissions, exporting to different formats, etc].

**Comment by tiritea** [comment]
I was also re-thinking that perhaps my originally suggested:

![49179125-7b1e9780-f3b6-11e8-8c2f-80ddf4027909](https://user-images.githubusercontent.com/18408635/49482889-d5779680-f895-11e8-8437-67dd5fbc0175.png)

may not be the best icon to represent a failed submit/send. Assuming submission is an all-or-nothing affair (that is, you dont get a partial submission persisted on the server) then the cloud icon is somewhat misleading, because its does not actually represent the *current state of the form* (!); rather, just that a previous attempted state transition happened to fail.

Because, after a failed submit, the form is still in a completed state sitting on the device, then I might suggest this would be better:

![icons8-ok-filled-75](https://user-images.githubusercontent.com/18408635/49483023-7b2b0580-f896-11e8-9de6-3c129ccdaf78.png)

which indicates, quite correctly, that the form is (still) complete, but that something went wrong and needs attention. Selecting a form in this state could bring up what the (submit) error is about, which is what you normally expect when clicking on something with an attention badge.

**Comment by cooperka** [comment]
We've updated the set of proposed icons to remove the clipboard icon and polish them up. The original post now shows the new icons; here's the before/after for comparison:

<img width="721" alt="comparison" src="https://user-images.githubusercontent.com/2047062/49525274-65f4ad80-f87b-11e8-979a-5e54edb19818.png">

**Comment by cooperka** [comment]
As far as the eye/visibility icon, Tom suggested potentially removing that icon and disabling the row instead. The row would be grayed out per Android guidelines, and the icon would also become gray instead of colored. This should create a kind of "disabled" feel whilst also keeping the (correct) "uploaded" icon reminding the user that the upload did complete properly.

If the user taps the disabled row, they would be shown a Toast explaining either "This sent form can't be shown because the form it belongs to has been deleted" (if deleted) or "This sent form can't be shown because it's encrypted" (if encrypted).

**Comment by tiritea** [comment]
Is clip-sms is a transitory state that only shows whilst the  being uploaded (via SMS), after which if successful it goes to clip-check? If so, do you want a similar (presumably yellow) icon to display whilst its sending via regular (non-SMS) HTTP/IP?

Colors are nice: blue=on device (local), yellow=in-flight (sending), green=on server.

which leaves red. But perhaps I'm over-analyzing... taken out of context, the red 'submit failed' icon doesn't actually convey the *current* state of the form (as I described previously), so its not clear what the situation is and what user should do. But in reality this is all going to appear *in context*; ie they've just attempted a submit, so if they soon after see the red 'failed' its immediately obvious what happened, that the form wasnt submitted, and as a consequence must is still on the device.

**Comment by cooperka** [comment]
> the red 'submit failed' icon doesn't actually convert the current state of the form

I agree that this icon could be misunderstood, but the way I view it, the error sign is shown on the thing that failed. In this case, if I saw a "form" icon with an error overlay I would assume something was wrong with the form. Whereas a cloud with an error overlay suggests something cloud-related failed. But that's just me.

Another similar interpretation of the red cloud is that the state of the form is "intended to have been submitted". It's a different state than a regular form because you really did intend to submit it, but something outside your control (the cloud) failed.

> do you want a similar (presumably yellow) icon to display whilst its sending via regular (non-SMS)

There's actually an alert dialog shown during regular submissions, so you couldn't really see the icon anyway. SMS submissions use the progress bar instead of the alert dialog. We thought to keep that behavior so as not to shake things up too much.

**Comment by tiritea** [comment]
> There's actually an alert dialog shown during regular submissions, so you couldn't really see the icon anyway.

K. Makes sense.

Presumably when Collect supports sending submission via IPoAC (https://en.wikipedia.org/wiki/IP_over_Avian_Carriers) as well as SMS you can indicate it with

![icons8-dove-filled-100](https://user-images.githubusercontent.com/18408635/49557125-7a17d800-f96b-11e8-8670-88e0ba548308.png)

😁

**Comment by smoyte** [comment]
Since we haven't heard any dissenting views here we are going to start implementing this as specified. Please let us know if there is anything else you'd like us to consider.

**Comment by yanokwa** [comment]
Only dissent at this stage is that I'm not sure how `clip-text` will look on a small screen. Even on my laptop, the checkboxes look a little cluttered. A empty clipboard and an empty clipboard with 2-3 lines might be clearer. Or just a doc?

I stole these from https://fontawesome.com, but you get the idea.
![clips](https://user-images.githubusercontent.com/32369/49768496-659c4e00-fc91-11e8-8ccb-9c3726c4e635.png)
![docs](https://user-images.githubusercontent.com/32369/49768580-9b413700-fc91-11e8-942d-83fa1488c557.png)

Or maybe instead of an actual checkmark, we used the stylized one from above.

**Comment by cooperka** [comment]
How's this @yanokwa?

<img width="700" alt="icons" src="https://user-images.githubusercontent.com/2047062/49812309-20305d00-fd33-11e8-9093-16164181468d.png">

**Comment by yanokwa** [comment]
Beautiful! And don't hate me if this is last minute, but I wonder if a document with a checkmark inside would be better for the finalized form?

**Comment by cooperka** [comment]
That sounds even better. Here's that change:

<img width="241" alt="screen shot 2018-12-12 at 22 25 29" src="https://user-images.githubusercontent.com/2047062/49913785-dc397700-fe5c-11e8-9d55-8e89d4a02af6.png">

I've got a good start on the implementation for this and it's going well. Thanks for the input everyone.

**Comment by cooperka** [comment]
[Feedback](https://github.com/opendatakit/collect/pull/2825#pullrequestreview-197733906) from @zestyping:

> I mostly like the icons, but I have concerns with two of them:
> 
> The "finalized" icon and the "uploaded" icon both use the same check mark, and I fear that may be confusing. If the check mark means "something was attempted, and it succeeded" then it pairs with the exclamation mark, and only makes sense for the "uploaded" icon. It seems the chief meaning of the "finalized" icon is that you can't edit the form anymore, which could be conveyed nicely by a small padlock; could there be a small lock icon in place of the checkmark?
> 
> The "sending" icon is a chat bubble, which doesn't look like any of the other form icons. Since it is related to network transmission, it seems like it should resemble the other cloud icons. How about a cloud with a simplified clock face inside, to indicate that transmission is scheduled?

**Comment by cooperka** [comment]
@zestyping I'd like to avoid re-opening too much of a discussion because icons are always hard to agree on, but you bring up fair questions that deserve explanation.

> The "finalized" icon

Finalized forms can actually still be edited; the state represents something more like "this form is **done** and ready to send" which is where the check mark inspiration came from. A padlock may make users think it's read-only which isn't the case.

The icon color is similar to that of the blank or partially filled form, and the document outline is there for further consistency, so I don't anticipate too many users being confused by the icon, but we can always revisit this if there end up being issues.

> The "sending" icon

We intentionally wanted this icon to look SMS-specific because it's only used for SMS submissions, not for Wifi submissions. Wifi submissions don't have a particular icon because there's a dialog that covers the screen while sending. The cloud seems too generic to be used for SMS.

However, if we were to eventually show the same UI for SMS and Wifi submissions, I think your cloud-with-clock suggestion would be perfect to represent both states. I'd like to leave this for later if you're okay with it.

**Comment by smoyte** [comment]
Thanks @cooperka. I'd kindly request that we go with the icons as currently spec'd. The Carter Center has been generous with supporting Kevin's time on this but we had finally reported to them that the designs were finally agreed to (over a month ago) and I really don't want to tell them that there is yet another iteration underway.

**Comment by yanokwa** [comment]
Agreed that we should proceed with the icons as is. I don't think users will be confused.

**Comment by zestyping** [comment]
That's fine with me!  I hope we have a chance to come back to the consistency concerns at a future point, but given the context it makes sense to go with this for now.
