### ISSUE TITLE
Match forms in local form list to server form list.

### ISSUE THREAD

**Issue by ggalmazor** [getodk/roadmap#34]
https://forum.opendatakit.org/t/have-collect-exactly-match-the-forms-on-central/23101/4

https://forum.opendatakit.org/t/openrosa-spec-proposal-add-matchexactly-attribute-to-form-list-response/23102

This is being discussed by the TSC

**Comment by lognaturel** [comment]
I think this can be moved to "in progress." The TSC went through a bunch of iteration over the last few months and we ended up starting with a Collect-only setting described [in the initial forum thread](https://forum.getodk.org/t/have-collect-exactly-match-the-forms-on-central/23101/9?u=ln). This will be in ODK Collect v1.28 due to be released in August.

Collect issues:
- https://github.com/GetODK/collect/issues/3934 Add "match exactly" mode
- https://github.com/GetODK/collect/issues/3959 Add "match exactly" error handling
- https://github.com/GetODK/collect/issues/3958 Add "match exactly" analytics
- https://github.com/GetODK/collect/issues/3961 Soft delete form definitions if device has corresponding form instances
- https://github.com/GetODK/collect/issues/3939 Add periodic "match exactly" updates
- https://github.com/getodk/collect/issues/3940 Add settings for "match exactly"

**Comment by tiritea** [comment]
> I think this can be moved to "in progress."

done.
